source 'https://rubygems.org'

gem 'attr_extras'
gem 'dry-inflector'
gem 'dry-monads'
gem 'dry-system'
gem 'dry-transformer'
gem 'dry-types'
gem 'pg'
gem 'sequel_pg'
gem 'rake'
gem 'rom'
gem 'rom-sql'
gem 'sqlite3'
